name: Build ARM + AMD
on:
  push:
    branches: [ "main" ]
    tags: [ '*.*.*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fhir-uml-server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # —‑‑‑ Java + Gradle cache ­‑‑‑———————————————————
      - name: Set up Temurin 21 and Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # ---------- Build SERVER ------------------------------------------------
      - name: Build server JAR
        working-directory: ./server
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon

      # ---------- Build CONVERTER --------------------------------------------
      - name: Build converter JAR
        working-directory: ./converter
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon

      # -------- ②  Build the image from the *already‑built* JARs --------------
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional – set "latest" tag when building from main
      - name: Set latest tag
        if: github.ref == 'refs/heads/main'
        run: echo "LATEST_TAG=latest" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ env.LATEST_TAG }}
          flavor: |
            latest=false

      - name: Build & push multi‑arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
